### ISSUE TITLE
Apache 2.4 release?

### ISSUE THREAD

**Issue by hexfusion** [gavincarr/mod_auth_tkt#22]
Can the current support for Apache 2.4 be summarized?

From quickly reading the tickets/PR's and code notes it  seems 2.4 support is still in beta?  Since the last commit seems to be circa 2015 is it fair to say this is stable and could be released?

Any details on this would be greatly appreciated a 2.4 release would be great for this very useful module.  Thanks in advance!

**Comment by hexfusion** [comment]
Just to note we have been using this with apache 2.4 without issue for a few months.

**Comment by karpet** [comment]
Just bumping this question - I have also been using the `2.3.99b1` release with Apache 2.4 without any problems. I have opened #23 to bring the Perl module on par with the C module.
